### ISSUE TITLE
Allow use of config to filter out auth on push

### ISSUE THREAD

**Issue by pajanowski** [sebastiande/insomnia-plugin-git-sync#1]
Auth currently gets committed as plain text in the workspace.json.

I was thinking auth could be filtered out on the push and the flow could be controlled with a property in a config.json.
For accessibility, I was thinking putting a link under plugins to open the config in a text editor like so.
![image](https://user-images.githubusercontent.com/15318386/146204973-342530a5-61bf-4b62-b4c7-10d326ded0ad.png)

To avoid breaking current work flows, filtering wouldn't happen by default.

**Comment by sebastiande** [comment]
@pajanowski we are storing the auth things in a property file based fault and use template tags to insert it into the calls.

If I would simply strip the auth from the exported file the import is not possible anymore with stored auth - cause Insomnia would delete the auth upon import.

**Comment by sebastiande** [comment]
Had some thoughts about it again and I think it would be better if you use a plugin similar to our setup, or write your own to use template variables for your credentials. You can have a look at our plugin here: https://github.com/sebastiande/insomnia-plugin-fault-variables
