### ISSUE TITLE
Prettify Commits from Push

### ISSUE THREAD

**Issue by cgstag** [sebastiande/insomnia-plugin-git-sync#3]
Hello,

Currently, when someone pushes changes, the `.json` exported is sort of minified, which makes the commits difficult to read.
![image](https://user-images.githubusercontent.com/7314489/160855885-0ad7619f-4846-4689-9d2e-765c7d33ad07.png)

I suggest the plugin should attempt to prettify the JSON string before committing the file and pushing it to the remote.
I think this can be done relatively easily by changing the following line :  https://github.com/sebastiande/insomnia-plugin-git-sync/blob/main/Workspace.js#L61

with
```javascript
fs.writeFileSync(expFilename, JSON.stringify(expObj, null, 2));
```

I can submit the pull request, but first I want to make sure this project is open for contributions and such changes are valuable.

**Comment by sebastiande** [comment]
@cgstag thanks for the idea, makes it much easier to see what has changed!
For sure I'm open to pull requests :) but as it is that simple I just implemented and tested it and released 3.1.0

Feel free to update your plugin
